# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rollbaz < Formula
  desc "Fast Rollbar triage from your terminal"
  homepage "https://github.com/kevinsheth/rollbaz"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kevinsheth/rollbaz/releases/download/v0.1.1/rollbaz_0.1.1_darwin_amd64.tar.gz"
      sha256 "3fd645535d51fb3efeb9747776151611789ec47f34e489d895a44318da93ef6b"

      def install
        bin.install "rollbaz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kevinsheth/rollbaz/releases/download/v0.1.1/rollbaz_0.1.1_darwin_arm64.tar.gz"
      sha256 "e784d6db8f64b8e31170a4216b00499adac2869bfcc70d33a6d71ab4e980eed8"

      def install
        bin.install "rollbaz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinsheth/rollbaz/releases/download/v0.1.1/rollbaz_0.1.1_linux_amd64.tar.gz"
      sha256 "013246fe21f3c005441e58282bb846caaf9e596adaf48913ceef926744dfa66d"
      def install
        bin.install "rollbaz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinsheth/rollbaz/releases/download/v0.1.1/rollbaz_0.1.1_linux_arm64.tar.gz"
      sha256 "d2b6e3c5397efc70ff354f2551e3df28c27f7988cd68910a7685052e398c5459"
      def install
        bin.install "rollbaz"
      end
    end
  end

  test do
    system "#{bin}/rollbaz", "--help"
  end
end
